      - name: Run main.py
        env:
          ALPHA_KEY: ${{ secrets.ALPHA_KEY }}
          LINE_TOKEN: ${{ secrets.LINE_TOKEN }}
          LINE_USER_ID: ${{ secrets.LINE_USER_ID }}
        run: |
          python main.py
